name: island leadership network
favicon: null
layout_spectrum: 0.6521855583414435
typography_spectrum: 0.8015672208275646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.29627654678188264
  lightness: 0.8721405132673681
  saturation: 0.6097089538816363
  rhythmicContrast: 0.04862871556542814
purpose: []
